[package]
name = "dungeon_game"
version = "0.1.0"
edition = "2024"

[lib]
name = "dungeon_game"
path = "src/lib.rs"

[dependencies]

[dev-dependencies]
criterion = "*"

[[bench]]
name = "bench_minimum_hp"
harness = false